addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.5.1")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"         % "0.15.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
